
### Post new Customer

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers
Content-Type: application/json

{
  "surname": "Ejemplo",
  "name": "Apellido",
  "nif": "79063712H",
  "genre": "male"
}

### Post new Customer

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers
Content-Type: application/json

{
  "surname": "Nombre",
  "name": "Apell",
  "nif": "38910248C",
  "genre": "female"
}

### Post new Customer

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers
Content-Type: application/json

{
  "surname": "NombreEjemplo",
  "name": "ApellidoEjemplo",
  "nif": "12345678G",
  "genre": "male"
}

### Get all

GET https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers

### delete customers

DELETE https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers?nif=79063714H


### delete customer from id

DELETE https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers/663d1cdb122d11114e13cc21

### patch customer

PATCH https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers?nif=79063714H
Content-Type: application/json

{
  "surname": "Guillermo"
}

### patch from id

PATCH https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/customers/663d1d24122d11114e13cc26
Content-Type: application/json

{
  "name": "Plaza"
}