
### Post new Customer

POST http://localhost:3000/furnitures
Content-Type: application/json

{
  "name": "silla",
  "productCode": "20394256701A9823B",
  "material": "wood",
  "height": 140,
  "width": 100,
  "depth": 100,
  "warranty": 365,
  "color": "brown",
  "prize": 40
}

### An other post

POST http://localhost:3000/furnitures
Content-Type: application/json

{
  "name": "silla",
  "productCode": "2039427927941823B",
  "material": "plastic",
  "height": 140,
  "width": 100,
  "depth": 100,
  "warranty": 365,
  "color": "white",
  "prize": 20
}

### An other post

POST http://localhost:3000/furnitures
Content-Type: application/json

{
  "name": "mesa",
  "productCode": "2039427901A9823B",
  "material": "wood",
  "height": 140,
  "width": 100,
  "depth": 100,
  "warranty": 365,
  "color": "brown",
  "prize": 20
}

### Get all

GET http://localhost:3000/furnitures

### Get with one param

GET http://localhost:3000/furnitures?name=silla

### Get by color

GET http://localhost:3000/furnitures?color=brown

### Get with multiple params

GET http://localhost:3000/furnitures?name=silla&material=plastic

### delete furniture

DELETE http://localhost:3000/furnitures?productCode=20394272341A9823B


### delete furniture from id

DELETE http://localhost:3000/furnitures/663d3375d41706dcaee729ac

### patch furniture

PATCH http://localhost:3000/furnitures?productCode=20394272341A9823B
Content-Type: application/json

{
  "color": "red"
}

### patch from id

PATCH http://localhost:3000/furnitures/663d1d24122d11114e13cc26
Content-Type: application/json

{
  "name": "planta"
}