
### Post new Customer

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions
Content-Type: application/json

{
  "type": "purchase",
  "productCode": "20394256701A9823B",
  "providerCIF": "A12345638",
  "moneyAmount": 91829
}

### An other post

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions
Content-Type: application/json

{
  "type": "sell",
  "productCode": "20394256701A9823B",
  "customerNIF": "79063712H",
  "moneyAmount": 12334
}


### An other post without having this furniture item

POST https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions
Content-Type: application/json

{
  "type": "purchase",
  "productCode": "NEW94256701A9823B",
  "providerCIF": "A12345638",
  "moneyAmount": 234,
  "name": "planta",
  "material": "wood",
  "height": 100,
  "width": 50,
  "warranty": 238,
  "color": "green"
}


### Get all

GET https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions

### Get with param

GET https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions?customerNIF=79063712H

### delete provider

DELETE https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions?productCode=20394256701A9823B


### delete provider from id

DELETE https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions/663d3375d41706dcaee729ac

### patch provider

PATCH https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions?customerNIF=79063712H
Content-Type: application/json

{
  "productCode": "2039427927941823B"
}

### patch from id

PATCH https://ull-esit-inf-dsi-23-24-prct13-dsikea-api-3m1d.onrender.com/transactions/663d4dc985a717969a28cb34
Content-Type: application/json

{
  "name": "otro nombre"
}